channels:
- conda-forge
dependencies:
- python=3.12.3
- pip<=24.3.1
- pip:
  - mlflow==3.2.0
  - numpy==2.2.0
  - pandas==2.2.3
  - psutil==7.0.0
  - scikit-learn==1.6.0
  - scipy==1.14.1
  - xgboost==3.0.4
name: mlflow-env
